# Generated by Django 4.2.3 on 2023-07-19 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readbook',
            name='user_id',
        ),
        migrations.AddField(
            model_name='book',
            name='date_marked',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
